version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: chatinn
      POSTGRES_PASSWORD: chatinn
      POSTGRES_DB: chatinn
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatinn"]
      interval: 10s
      retries: 5

  api:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgres+asyncpg://chatinn:chatinn@db:5432/chatinn
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  db_data:
